services:
  # Backend Service
  - type: web
    name: healix-backend
    env: python
    buildCommand: cd medical_booking && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd medical_booking && gunicorn medical_booking.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: healix-db
          property: connectionString
      - key: DATABASE_NAME
        fromDatabase:
          name: healix-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: healix-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: healix-db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: healix-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: healix-db
          property: port
      - key: PYTHON_VERSION
        value: 3.11.0
    dependencies:
      - name: healix-db

  # Frontend Service
  - type: web
    name: healix-frontend
    env: node
    buildCommand: >
      cd frontend &&
      npm cache clean --force &&
      rm -rf node_modules .next package-lock.json &&
      npm install --legacy-peer-deps &&
      NEXT_PUBLIC_API_URL=https://healix-7515.onrender.com/ npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://healix-7515.onrender.com/
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

databases:
  - name: healix-db
    databaseName: healix
    user: healix
    plan: free
    ipAllowList: []