services:
  # Backend Service
  - type: web
    name: healix-backend
    env: python
    buildCommand: cd medical_booking && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd medical_booking && gunicorn medical_booking.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: healix-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Service
  - type: web
    name: healix-frontend
    env: node
    buildCommand: >
      cd frontend && 
      npm install -D tailwindcss postcss autoprefixer @tailwindcss/forms @tailwindcss/typography tailwindcss-animate && 
      npm install @radix-ui/react-dialog @radix-ui/react-select @radix-ui/react-slot class-variance-authority clsx tailwind-merge lucide-react @hookform/resolvers react-hook-form zod @radix-ui/react-label @radix-ui/react-toast && 
      npm install && 
      NEXT_FONT_GOOGLE=false npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://healix-7515.onrender.com/
      - key: NEXT_FONT_GOOGLE
        value: false

databases:
  - name: healix-db
    databaseName: healix
    user: healix
    plan: free